---
title: Brainship
timezone: UTC
collections:
  java_articles:
    title: Java Articles
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: info@brainship.com
description: 'Brainship is the place for becoming a better software developer. Whether
  you are a beginner or someone who is looking to get to the next level, we welcome
  you to use us to further our skill set.  Our main motto is, get stuff done!

'
baseurl:
url:
twitter_username: brainshiphq
github_username: brainship
markdown: kramdown
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
permalink: pretty
